// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB63KL0MC71dA8yIGrZ2Vy5pUKGxVu02ok',
    appId: '1:519109200908:web:3e202f68d7439e6bafb229',
    messagingSenderId: '519109200908',
    projectId: 'chain-reaction-1',
    authDomain: 'chain-reaction-1.firebaseapp.com',
    storageBucket: 'chain-reaction-1.appspot.com',
    measurementId: 'G-YXBMNFH664',

    databaseURL: 'https://chain-reaction-1-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAol5Jqy-ZxDtZhheuksk4Iu9GiMMx2lHE',
    appId: '1:519109200908:android:95b44f2803ce7a9dafb229',
    messagingSenderId: '519109200908',
    projectId: 'chain-reaction-1',
    storageBucket: 'chain-reaction-1.appspot.com',

    databaseURL: 'https://chain-reaction-1-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVRCYBZmDhxyXRIQT9fvUeJGNBrOkf7Gs',
    appId: '1:519109200908:ios:96c90125b3461cb2afb229',
    messagingSenderId: '519109200908',
    projectId: 'chain-reaction-1',
    storageBucket: 'chain-reaction-1.appspot.com',
    iosBundleId: 'com.example.chainReaction',

    databaseURL: 'https://chain-reaction-1-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVRCYBZmDhxyXRIQT9fvUeJGNBrOkf7Gs',
    appId: '1:519109200908:ios:c5efba0cac422169afb229',
    messagingSenderId: '519109200908',
    projectId: 'chain-reaction-1',
    storageBucket: 'chain-reaction-1.appspot.com',
    iosBundleId: 'com.example.chainReaction.RunnerTests',

    databaseURL: 'https://chain-reaction-1-default-rtdb.firebaseio.com',
  );
}
